name: my-workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy Node.js - bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Run linting
        run: bun run lint

      - name: Build application
        run: bun run build
